version: "3.9"
services:
  app:
    container_name: nodejs-boilerplate
    restart: always
    build: .
    ports:
      - "8081"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
